### ISSUE TITLE
highlighting too many terms causes highlighter to return nothing

### ISSUE THREAD

**Issue by jeacott** [wikimedia/search-highlighter#13]
I'm using the latest release of this plugin 1.4.1 with ES 1.4.2

in the following query I've manually expanded the fields to overcome problems with the highlighter 
and wildcard queries (it seems to arbitrarily decide not to return any highlights depending on the query fields - possibly related to internal expansion and this 'too many terms' issue.) eg if I have in my primary search transcript.en*.p.text, then it may or may not work.

I've tried it against indexes with "index_options":"offsets", and with
                        "term_vector" :"with_positions_offsets"
but it doesnt seem to make much difference with this issue.
 
manually expanding the terms in the highlighter results does give a more consistent result, and below I've omitted all but the first entry for the highlighter fields for brevity.

with this many terms in the main query OR the highlight_query, I get zero highlighted results from this experimental highlighter (there is no error) where the fvh highlighter returns good results. 
If I reduce the number of terms I get results from this highlighter.

the issue only seems to affect queries where phrase_prefix is used, but it doesn't occur in every query with a phrase_prefix in it. 
When it occurs for a given query (irrespective of the query terms) it consistently fails.

if I have a phrase_prefix query ONLY as a highlight_query, and nowhere in the main query then it seems to give results, but if I have it in both it doesn't.

neither the fvh nor this highlighter seem to respect the common terms cutoff frequency hence my use below of the highlight_query

I realise this is a bit vague, but I cant pin down exactly what seems to be going on. I love this highlighter mainly due to the fetch_fields feature which improves my performance hugely so I'm very keen to have/help have the issue resolved.

any hints/help greatly appreciated.

```
{
  "from" : 0,
  "size" : 10,
  "query" : {
    "filtered" : {
      "query" : {
        "bool" : {
          "must" : {
            "multi_match" : {
              "query" : "to influence",
              "fields" : [ "transcript.en.p.text", "transcript.en-AU.p.text",  "transcript.en-BZ.p.text",  "transcript.en-CA.p.text",  "transcript.en-CB.p.text",  "transcript.en-GB.p.text",  "transcript.en-IE.p.text", "transcript.en-JM.p.text", "transcript.en-NZ.p.text",  "transcript.en-PH.p.text", "transcript.en-TT.p.text",  "transcript.en-US.p.text", "transcript.en-ZA.p.text", "transcript.en-ZW.p.text" ],
              "type" : "phrase_prefix",
              "slop" : 2,
              "minimum_should_match" : "75%",
              "cutoff_frequency" : 0.01
            }
          },
          "should" : {
            "multi_match" : {
              "query" : "to influence",
              "fields" : ["title^0.2", "description^0.7" ],
              "type" : "best_fields",
               "cutoff_frequency" : 0.01
            }
          }
        }
      },
    }
  },
  "min_score" : 1.8E-5,
  "highlight" : {
    "order" : "score",
    "type" : "experimental",
    "highlight_query" : {
      "multi_match" : {
        "query" : "to influence",
        "fields" : ["transcript.en.p.text", "transcript.en-AU.p.text",  "transcript.en-BZ.p.text",  "transcript.en-CA.p.text",  "transcript.en-CB.p.text",  "transcript.en-GB.p.text",  "transcript.en-IE.p.text", "transcript.en-JM.p.text", "transcript.en-NZ.p.text",  "transcript.en-PH.p.text", "transcript.en-TT.p.text",  "transcript.en-US.p.text", "transcript.en-ZA.p.text", "transcript.en-ZW.p.text"],
        "type" : "phrase_prefix",
        "slop" : 2
      }
    },
    "fields" : {
      "transcript.en.p.text" : {
        "fragment_size" : 150,
        "number_of_fragments" : 10,
        "fragmenter" : "scan",
        "options" : {
          "hit_source" : "postings",
          "skip_if_last_matched" : false
        }
      }
... more follow 
    }
  }
}
```

**Comment by jeacott** [comment]
ok,
 so this issue here is simple. there are a bunch of query types and features that are not implemented.
I've added FunctionScoreQuery and FiltersFunctionScoreQuery for my own needs, 
when I find some time I'll add phrase prefix and make a pull request.

Cheers.

**Comment by nik9000** [comment]
@jeacott I wouldn't be surprised about FunctionScoreQuery and FiltersFunctionScoreQuery - as you've probably seen they all have to be manually accounted for. So the ones I'm likely to have missed some of the ones I don't use frequently.

Sorry I hadn't seen this 20 days ago - I thought I was subscribed to the project but I'm not getting consistent emails from it.

If you expect to put together a pull request I'll certainly review and merge. I expect to make a release sometime in the next few days for https://phabricator.wikimedia.org/T95021.

**Comment by nik9000** [comment]
I've got a patch together for FunctionScoreQuery and FiltersFunctionScoreQuery that I'll certainly get into the release. I'll have a look at the common terms issue next.

**Comment by nik9000** [comment]
https://gerrit.wikimedia.org/r/207432

**Comment by nik9000** [comment]
I've also figured out the trouble with too many terms. I'll write up a patch for that and some more extensive documentation around what is going on.

**Comment by jeacott** [comment]
Looks great. Thank you! I'll give it a run.
