### ISSUE TITLE
Do you have plans to update this plugin so that it works with current versions of elasticsearch?

### ISSUE THREAD

**Issue by linkwoman** [wikimedia/search-highlighter#15]
Hi there.  Thanks for the plugin.  Do you have plans to update it so that it works with current versions of elasticsearch?
Kibana4 requires 1.4.4, and elasticsearch is up to 1.5.x  

thanks!

**Comment by nik9000** [comment]
1.4.4 _should_ work. The master branch is built against 1.4.1 right now and I don't expect huge changes between 1.4.1 and 1.4.4. Let me know if it isn't working for you.

I plan to cut a 1.5.x in a few days actually. Late this week or early next week. I'm finishing up some changes right now that'll then I have to do some on CirrusSearch to use them, get a beta deploy, and after that I should have time for a 1.5 compatible release.

**Comment by linkwoman** [comment]
Cool! I'll try it again and let you know what the exact problem was.  Looking forward to the 1.5.x version!  :-)
