### ISSUE TITLE
elasticsearch 2.0 support

### ISSUE THREAD

**Issue by rpedela** [wikimedia/search-highlighter#18]
Are there any plans to support Elasticsearch 2.0?

**Comment by andreip** [comment]
bump

**Comment by dtran320** [comment]
+1

**Comment by wallaceferreira** [comment]
+1

**Comment by wkiser** [comment]
+1

**Comment by rpedela** [comment]
@nomoa Thanks for updating the code to support ES 2.3.2. Are there any plans to create releases so that ```/bin/plugin install``` works?

**Comment by nomoa** [comment]
@rpedela: sure, I'll do that very soon (hopefully monday). The artifacts are still in the staging repo, we just deployed the code yesterday in our beta cluster for a very final test.

**Comment by j23d** [comment]
Thanks for the update and good to read that its in testing stage. Would be great to have this soon.

**Comment by nomoa** [comment]
Sorry for the long delay. I just promoted 2.3.3 in central and can be installed with:

```
bin/plugin install org.wikimedia.search.highlighter/experimental-highlighter-elasticsearch-plugin/2.3.3
```

Commits should arrive soon on this github mirror.
I plan to release the plugin for some older elastic versions, Ideally the last version of 2.0.x, 2.1.x, 2.2.x.
Please comment this ticket or open a new one if you need a particular one.

I'll try to update the plugin more regularly in the future.

**Comment by rpedela** [comment]
Awesome! Thanks.
