### ISSUE TITLE
plugin install for ES 5.1.2

### ISSUE THREAD

**Issue by rpedela** [wikimedia/search-highlighter#26]
Thanks for updating the plugin for 5.x. However the current command do not seem to work. Has the command changed or is the version not available yet?

**Comment by nomoa** [comment]
The plugin is available but the syntax of the install command has slightly changed:
`bin/elasticsearch-plugin install org.wikimedia.search.highlighter:experimental-highlighter-elasticsearch-plugin:5.1.2`
I'll update the doc.

**Comment by rpedela** [comment]
Thanks!
