### ISSUE TITLE
parse error: Invalid \uXXXX\uXXXX surrogate pair escape

### ISSUE THREAD

**Issue by doublex** [wikimedia/search-highlighter#32]
The highlighter creates wrong json on 4-byte UTF-8 codepoints.
Steps to reproduce:

````
curl -XPUT 'localhost:9200/index/test/1?pretty' -d '
{
  "message":"Lorem ipsum dolor sit amet, consectetur, adipisci velit \uD83D\uDC4A\uD83D\uDC4A\uD83D\uDC4A\uD83D\uDC4A\uD83D\uDC4A\uD83D\uDC4A\uD83D\uDC4A\uD83D\uDC4A\uD83D\uDC4A\uD83D\uDC4A\uD83D\uDC4A\uD83D\uDC4A\uD83D\uDC4A\uD83D\uDC4A\uD83D\uDC4A\uD83D\uDC4A\uD83D\uDC4A\uD83D\uDC4A\uD83D\uDC4A\uD83D\uDC4A\uD83D\uDC4A\uD83D\uDC4A\uD83D\uDC4A\uD83D\uDC4A\uD83D\uDC4A\uD83D\uDC4A\uD83D\uDC4A"
}'
````

````
curl -XGET 'localhost:9200/index/test/_search?pretty' -d '
{
  "query": { "match": { "message": "velit" } },
  "highlight": {"fields":{"message":{"type":"experimental","fragment_size": 50}}}
}'
````

Everything is parseable, but "hits" -> "hits" -> "highlight" -> "message".
Piping the result-query to "jq .":
parse error: Invalid \uXXXX\uXXXX surrogate pair escape at line 23, column 177

**Comment by nomoa** [comment]
thanks for the report, yes it's probable that the segmenter is confused in such situation and simply bails out on max length and arbitrarily cut a surrogate pairs in half.

I suppose this bug might happen if the big fragment is before the highlighted term.
I'll try to find some time to fix this.

**Comment by doublex** [comment]
A quick solution could be:
````
if( (last_surrogate & 0xF800) == 0xD800 ) {
    // take one more surrogate
}
````
