### ISSUE TITLE
Does the plugin work with version 6.x

### ISSUE THREAD

**Issue by seranus** [wikimedia/search-highlighter#33]
My problem is that I need text positions of search results and after doing some research it seems that this plugin is the only way to do it without coding.

What's the highest version of elastics this can run on so i can downgrade and/or are there plans for making it run on 6?

**Comment by gehel** [comment]
We have not upgraded yet to elasticsearch 6.x. We do have plans for that upgrade, but probably not before June. Currently, the highest version that we have tested is 5.5.2.

Feel free to recompile against 6.x and report any issue! Or even better, submit patches! Note that this github repo is a mirror of our main repository on [gerrit](https://gerrit.wikimedia.org/). See [Developer Access](https://www.mediawiki.org/wiki/Developer_access) for slightly more details.
