### ISSUE TITLE
Elasticsearch Keyword not getting highlighted

### ISSUE THREAD

**Issue by hirik** [wikimedia/search-highlighter#35]
Hi, 
I'm using elasticsearch version 7.0.0 and search-highlighter 6.5.4. When I tried to match a "KEYWORD" field, highlight results are not populated but the same code working fine for the "TEXT" field. Any help or document reference is appreciated. 

            final HighlightBuilder highlightBuilder = new HighlightBuilder();
            highlightBuilder.highlighterType("experimental");
            final Map<String , Object> options = new HashMap<>();
            options.put("return_offsets" , true);
            highlightBuilder.options(options);

**Comment by nomoa** [comment]
Please share the mapping and the query you're using so that we cant try to reproduce the issue.
Thank you.

**Comment by hirik** [comment]
Hi, 

Query:
```
{
    "query" : {
        "match" : {"keyword_type": "LogAlways"}
    },
    "highlight" : {
       
    "fields": {
      "type": {
      	 "keyword_type": "experimental",
        "number_of_fragments": 1,
        "options": {
          "return_offsets": true
        }
      }
    }

    }
}
```
Response 

```
{
    "took": 145,
    "timed_out": false,
    "_shards": {
        "total": 1,
        "successful": 1,
        "skipped": 0,
        "failed": 0
    },
    "hits": {
        "total": {
            "value": 10000,
            "relation": "gte"
        },
        "max_score": 0.4709578,
        "hits": [
            {
                "_index": "index1",
                "_type": "event",
                "_id": "1_0000-aa60",
                "_score": 0.4709578,
                "_source": {
                    "time_at": 1556257721992,
                    "keyword_type": "LogAlways",
                }
            }
        ]
    }
}

```

Mapping


```
 "mappings": {
            "dynamic_templates": [
                {
                    "Epoch": {
                        "match": "time_*",
                        "mapping": {
                            "format": "epoch_millis",
                            "type": "date"
                        }
                    }
                },
                {
                    "Text": {
                        "match": "text_*",
                        "mapping": {
                            "type": "text"
                        }
                    }
                },
                {
                    "Keyword": {
                        "match": "keyword_*",
                        "mapping": {
                            "normalizer": "lowercase_normalizer",
                            "type": "keyword"
                        }
                    }
                }
            ],
            "properties": {
                "time_at": {
                    "type": "date",
                    "format": "epoch_millis"
                },
                "text_description": {
                    "type": "text"
                },
                "keyword_type": {
                    "type": "keyword",
                    "normalizer": "lowercase_normalizer"
                }
            }
        }
```

**Comment by hirik** [comment]
I think the problem might be the input letter case. When I try with lowercase it works

**Comment by hirik** [comment]
@nomoa is there any solution or workaround to solve this case?

**Comment by nomoa** [comment]
@hirik there's definitely an issue to fix but I may not be able to dedicate some time to fixing it anytime soon. I think a workaround would we be not to use the type: keyword but use type: text with the keyword tokenizer, basically something that does not use the `normalizer` attribute.

**Comment by hirik** [comment]
@nomoa thanks for your reply. If possible please let me know where to start to identify this issue(module or package or java file), I will try to fix this issue.

**Comment by nomoa** [comment]
@hirik I started to work on this issue today https://gerrit.wikimedia.org/r/c/search/highlighter/+/518250
It should be avialable on this github repo as soon as it's reviewed under gerrit.

**Comment by hirik** [comment]
@nomoa thanks for the update.
