### ISSUE TITLE
How to install from source?

### ISSUE THREAD

**Issue by ArturFormella** [wikimedia/search-highlighter#38]
Hello!
I have downloaded sources, compiled and then I get stuck.

pom.xml:
```
-        <elasticsearch.version>7.5.1</elasticsearch.version>
+        <elasticsearch.version>7.6.2</elasticsearch.version>
-        <lucene.version>8.3.0</lucene.version>
+        <lucene.version>8.4.0</lucene.version>
```

/src/main/java/org/wikimedia/highlighter/experimental/elasticsearch/FieldWrapper.java
```
-    MappedFieldType fieldType = context.context.getMapperService().fullName(fieldName);
+    final MappedFieldType fieldType = context.context.getMapperService().fieldType(fieldName);
```

```
mvn -Denforcer.skip=true -Dmaven.test.skip=true -DskipTests package
mvn -Denforcer.skip=true -Dmaven.test.skip=true -DskipTests install
```

ES error:
`unknown highlighter type [experimental] for the field [content]`

How to add plugin to Elasticsearch?

**Comment by nomoa** [comment]
After running `./mvnw package` you'll find the zip file to install in `experimental-highlighter-elasticsearch-plugin/target/releases/experimental-highlighter-elasticsearch-plugin-X.Y.Z-SNAPSHOT.zip`
Then use this file with the elasticsearch tool to install plugins: see https://www.elastic.co/guide/en/elasticsearch/plugins/current/plugin-management-custom-url.html

`mvn install` does not install anything to elasticsearch it will install the compiled artifacts to your local maven repository.

**Comment by ArturFormella** [comment]
```
# /usr/share/elasticsearch/bin/elasticsearch-plugin install \
  file:///usr/share/elasticsearch/data/search-highlighter/experimental-highlighter-elasticsearch-plugin/target/releases/experimental-highlighter-elasticsearch-plugin-7.5.2-SNAPSHOT.zip
```
It has been installed:
```
# /usr/share/elasticsearch/bin/elasticsearch-plugin list
experimental-highlighter
```
It's important to remember to restart the elasticsearch cluster.
Now it works. Thanks!

**Comment by nomoa** [comment]
Closing this ticket as your problem seems to be resolved.
If you are making changes to support a new elastic version please feel free to submit a PR with your code.

Thanks!
